services:
  db:
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "todo"
      TZ: "Asia/Tokyo"
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
